//importing all the controller
import "../controllers/user/signUp.controller"
import "../controllers/user/verifyCode.controller"
import "../controllers/user/login.controller"
import "../controllers/test.controller"
import "../controllers/client/addClient.controller"
import "../controllers/client/getclients.controller"
import "../controllers/user/getUser.controller"
import "../controllers/invoice/createInvoice.controller"
import "../controllers/invoice/getInvoices.controller"
import "../controllers/invoice/getOneInvoice.controller"
import "../controllers/invoice/InvoicePaid.controller"
